# Generated by Django 4.2.11 on 2024-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Revoked', 'Revoked')], default='Active', max_length=8),
        ),
    ]
