# Generated by Django 4.2.11 on 2024-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Revoked')], default='A', max_length=8),
        ),
    ]
